import json
import random
import re
from collections import Counter
from typing import Dict, List, Optional

from study_buddy.ollama_client import OllamaClient
from study_buddy.text_utils import important_words, split_sentences


def _find_answer(sentence: str, common_terms: List[str]) -> str:
    title_terms = re.findall(r"\b[A-Z][a-zA-Z]{3,}\b", sentence)
    if title_terms:
        return title_terms[0]

    for term in common_terms:
        if re.search(rf"\b{re.escape(term)}\b", sentence, flags=re.IGNORECASE):
            return term

    words = important_words(sentence)
    return words[0] if words else ""


def generate_quiz(text: str, question_count: int = 5) -> List[Dict[str, object]]:
    """Generate simple fill-in-the-blank multiple choice questions."""
    sentences = split_sentences(text)
    common_terms = [term for term, _ in Counter(important_words(text)).most_common(30)]

    questions = []
    used_answers = set()

    for sentence in sentences:
        answer = _find_answer(sentence, common_terms)
        if not answer or answer.lower() in used_answers:
            continue

        blanked = re.sub(rf"\b{re.escape(answer)}\b", "_____", sentence, count=1, flags=re.IGNORECASE)
        if blanked == sentence:
            continue

        distractors = [term for term in common_terms if term.lower() != answer.lower()]
        random.shuffle(distractors)

        options = [answer] + distractors[:3]
        if len(options) < 4:
            continue

        random.shuffle(options)
        questions.append(
            {
                "question": f"Fill in the blank: {blanked}",
                "options": options,
                "answer": answer,
                "source": sentence,
            }
        )
        used_answers.add(answer.lower())

        if len(questions) >= question_count:
            break

    return questions


def generate_llm_quiz(text: str, model_name: str = "phi3", question_count: int = 5) -> Optional[List[Dict[str, object]]]:
    """Generate conceptual MCQ quiz questions using the local Ollama LLM.

    Returns None if Ollama is not available, so the caller can fall back
    to the fill-in-the-blank method.
    """
    client = OllamaClient(model_name=model_name)
    if not client.is_available():
        return None

    trimmed = text[:3000]

    prompt = f"""You are a study quiz generator. Create exactly {question_count} multiple-choice questions from the text below.

Rules:
- Test understanding and concepts, not just vocabulary
- Each question must have exactly 4 options: A, B, C, D
- Exactly one option must be correct
- Return ONLY valid JSON, no other text

Return a JSON array in this exact format:
[
  {{
    "question": "What is ...?",
    "options": ["option A", "option B", "option C", "option D"],
    "answer": "option A",
    "source": "The relevant sentence from the text"
  }}
]

Text:
{trimmed}

JSON:"""

    try:
        response = client.generate(prompt)
        # Try to extract JSON from the response
        response = response.strip()

        # Find JSON array in the response
        start = response.find("[")
        end = response.rfind("]")
        if start == -1 or end == -1:
            return None

        json_str = response[start : end + 1]
        parsed = json.loads(json_str)

        # Validate structure
        validated = []
        for item in parsed:
            if (
                isinstance(item, dict)
                and "question" in item
                and "options" in item
                and "answer" in item
                and isinstance(item["options"], list)
                and len(item["options"]) == 4
                and item["answer"] in item["options"]
            ):
                validated.append({
                    "question": item["question"],
                    "options": item["options"],
                    "answer": item["answer"],
                    "source": item.get("source", "Generated by AI"),
                })

        return validated[:question_count] if len(validated) >= 2 else None

    except (json.JSONDecodeError, Exception):
        return None
